version: '3.8'

services:
  app:
    build: .
    container_name: avito-reviewer-app
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "postgres://user:password@db:5432/reviewer_db?sslmode=disable"
      HTTP_PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: avito-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reviewer_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d reviewer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: